local_costmap:
  #TODO global_frame
  global_frame: /odom
  # global_frame: /odom
  robot_base_frame: base_footprint
  update_frequency: 20.0
  publish_frequency: 10.0
  static_map: false
  rolling_window: true
  width: 5
  height: 5
  resolution: 0.25
  transform_tolerance: 0.5
  
  plugins:
   - {name: static_layer,        type: "costmap_2d::StaticLayer"}
   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
